<h1><b> DIGIT CLASSIFICATION-MNIST USING FEEDFORWARD NEURAL NETWORK</b></h1>

In [2]:
#Load The Necessary Dependencies
import numpy as np
import cv2
import pandas as pd
import matplotlib.pyplot as plt
import time
import pickle


In [3]:
#load the datasets
trainSet=pd.read_csv(r"D:\Datasets\MNIST\mnist_train.csv")
testSet=pd.read_csv(r"D:\Datasets\MNIST\mnist_test.csv")


trainSet.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [6]:
 #Load the training data into array
train_x=np.array(trainSet.iloc[:,1:],dtype=np.float32)
train_x=train_x.reshape(-1,28*28)

train_x=train_x/255.0

#Load the desired output
train_y=np.array(trainSet.iloc[:,0])





In [9]:
import numpy as np
#Actual Code For The Model
class DigitClassifier:
    def __init__(self,learning_rate,epoch,neuron_no):
        self.learning_rate=learning_rate
        self.epoch=epoch
        self.neuron_no=neuron_no


    def ReLU(self,x):
        return np.maximum(0.01*x,x)
    
    def softmax(self,z):
        exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))  
        return exp_z / np.sum(exp_z, axis=1, keepdims=True)

    def ReLU_gradient(self,x):
        return np.where(x>0,1,0.01)

    def one_hot_encoding(self,y,size):
        b=np.eye(size)[y]
        print(f"Hot encoded : {b}")
        return b

    
    
    def train(self,x,y):
        self.m,self.n=x.shape
        self.y=self.one_hot_encoding(y,10)
        self.init_weights()
        self.x=x
     
        for i in range(self.epoch):
            print("Iteration "+str(i))
            self.forward_prop()
            if i % 10 == 0:
                predictions = self.predict(self.x)
                accuracy = np.mean(np.argmax(predictions, axis=1) == y) * 100
                print(f"Training Accuracy: {accuracy:.2f}%")
            self.backward_prop()
    
    def init_weights(self):
        self.w1 = np.random.randn(self.n,self.neuron_no)*(np.sqrt(2./self.n))
        self.b1 = np.zeros(self.neuron_no)
        self.w2 = np.random.randn(self.neuron_no,self.neuron_no)*(np.sqrt(2./self.neuron_no))
        self.b2 = np.zeros(self.neuron_no)
        self.w3 = np.random.randn(self.neuron_no,10)*(np.sqrt(2./self.neuron_no))
        self.b3 = np.zeros(10)


    def forward_prop(self):
        self.z1 = np.dot(self.x, self.w1) + self.b1
        self.o1 = self.ReLU(self.z1)
        
        self.z2 = np.dot(self.o1, self.w2) + self.b2
        self.o2 = self.ReLU(self.z2)
        
        self.z3 = np.dot(self.o2, self.w3) + self.b3

        self.o3 = self.softmax(self.z3)
        
    def backward_prop(self):
        error3=self.o3-self.y
        dw3=np.dot(self.o2.T,error3)/self.m
        db3=np.sum(error3,axis=0)/self.m
        self.w3-=self.learning_rate*dw3
        self.b3-=self.learning_rate*db3


        error2=np.dot(error3,self.w3.T)*self.ReLU_gradient(self.o2)
        dw2=np.dot(self.o1.T,error2)/self.m
        db2=np.sum(error2,axis=0)/self.m
        self.w2-=self.learning_rate*dw2
        self.b2-=self.learning_rate*db2

        error1=np.dot(error2,self.w2.T)*self.ReLU_gradient(self.o1)
        dw1=np.dot(self.x.T,error1)/self.m
        db1=np.sum(error1,axis=0)/self.m
        self.w1-=self.learning_rate*dw1
        self.b1-=self.learning_rate*db1

    
    
    def predict(self,x):
        z1=np.dot(x,self.w1)+self.b1
        o1=self.ReLU(z1)
        z2=np.dot(o1,self.w2)+self.b2
        o2=self.ReLU(z2)
        z3=np.dot(o2,self.w3)+self.b3
        o3=self.softmax(z3)
        return o3


In [18]:
#Create An Instance of The DigitClassifier Class
model=DigitClassifier(0.1,250,16)
start_time=time.time()
model.train(train_x,train_y)
end_time=time.time()

print("Training Complete " )
print(f"Training Time: {end_time - start_time} seconds")





Hot encoded : [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
Iteration 0
Training Accuracy: 10.30%
Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5
Iteration 6
Iteration 7
Iteration 8
Iteration 9
Iteration 10
Training Accuracy: 37.20%
Iteration 11
Iteration 12
Iteration 13
Iteration 14
Iteration 15
Iteration 16
Iteration 17
Iteration 18
Iteration 19
Iteration 20
Training Accuracy: 43.27%
Iteration 21
Iteration 22
Iteration 23
Iteration 24
Iteration 25
Iteration 26
Iteration 27
Iteration 28
Iteration 29
Iteration 30
Training Accuracy: 51.59%
Iteration 31
Iteration 32
Iteration 33
Iteration 34
Iteration 35
Iteration 36
Iteration 37
Iteration 38
Iteration 39
Iteration 40
Training Accuracy: 71.93%
Iteration 41
Iteration 42
Iteration 43
Iteration 44
Iteration 45
Iteration 46
Iteration 47
Iteration 48
Iteration 49
Iteration 50
Training Accuracy: 78.36%
Iteration 51
Iteratio

<h2><b> The train accuracy of the model is around 90.05% which is considerable</b></h2>

In [19]:
#Save the model's weights and biases  for usage  in GUI
np.savez('model_weights_biases.npz', w1=model.w1, b1=model.b1, w2=model.w2, b2=model.b2,w3=model.w3,b3=model.b3)

<h3><b> These trained weights are exported for usage in the  main Classifier Application</b></h3>

In [20]:
#Test The Model 
test_x=np.array(testSet.iloc[:,1:])
test_x.reshape(-1,28*28)
test_x=test_x/255.0


#Load the desired output
test_y=np.array(testSet.iloc[:,0])
test_y.shape



(10000,)

In [21]:


predicted=model.predict(test_x)
predicted_labels=np.argmax(predicted,axis=1)
count=predicted_labels==test_y
print(f" Test Accuracy ={np.mean(predicted_labels == test_y) * 100}%")
    




 Test Accuracy =90.42999999999999%


<h1><b>Overall , the model works quite well with a test accuracy in range 90%</b></h1>